### ISSUE TITLE
Release description ends with %0A

### ISSUE THREAD

**Issue by Erriez** [Roang-zero1/github-create-release-action#18]
My `CHANGELOG.md` contains the text:

```
$ cat CHANGELOG.md
# Changelog

## v1.0.0

Initial Release.
```

The created release contains description: `Initial Release.%0A`. It contains additional `%0A` characters at the end.

```yaml
on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

jobs:
  build:
    ...
  release:
    name: "Create release"
    needs: build
    runs-on: ubuntu-latest
    if: contains(github.ref, '/tags/v')

    steps:
      - uses: actions/checkout@v3

      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@v3
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

```
$ hexdump -C CHANGELOG.md 
00000000  23 20 43 68 61 6e 67 65  6c 6f 67 0a 0a 23 23 20  |# Changelog..## |
00000010  76 31 2e 30 2e 30 0a 0a  49 6e 69 74 69 61 6c 20  |v1.0.0..Initial |
00000020  52 65 6c 65 61 73 65 2e                           |Release.|
00000028
```

Tried with and without a newline (\n = 0x0A) at the end of the file.

Any suggestion?
