### ISSUE TITLE
How can I use tag message as description?

### ISSUE THREAD

**Issue by damirka** [Roang-zero1/github-create-release-action#5]
Hello! 

How can I use tag message (`git tag -a v0.0.1 -m "message"`) as a description for my release? Does your action have this function?

**Comment by leycec** [comment]
Coincidentally, that's *exactly* what I was grepping for. Sadly, this action only parsers release notes from `CHANGELOG.md` files. That's awkward, as changelogs are largely redundant in the git era. After all, git *already* provides a trivial changelog guaranteeably synchronized across all repository changes. It's called `git log`. Since we have `git log`, we don't need `CHANGELOG.md`. Don't Repeat Yourself (DRY), eh?

Like you and presumably most authors, I just embed release notes as annotated tag messages. Fortunately, the [alternative `create-release` action](https://github.com/actions/create-release) already supports exactly that via the `${{ github.event.commits[0].message }}` template variable, which GitHub Actions dynamically replaces with the message for the HEAD commit hopefully corresponding to this tag: e.g.,

```
      - id: github-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Stable Release ${{ github.ref }}
          body: ${{ github.event.commits[0].message }}
```

Yes, that should be *much* better documented somewhere. Like, anywhere.
